### ISSUE TITLE
Hitting the edit button to save any edits to a field errors out et. al

### ISSUE THREAD

**Issue by hifihedgehog** [FriendsOfFlarum/masquerade#26] opened 2018-04-20 03:28 UTC
There are two problems that are part of this release. First, wherever I hit the edit button to try to save an edit to a field, I get _"Oops! Something went wrong. Please reload the page and try again."_ Second, if I am just beginning to make a field of the type dropdown menu and try adding more than one option, the extension just saves and closes after hitting the plus sign for a second option.

**Comment by clarkwinkelmann** [comment] 2018-04-20 14:58
Could you try getting the full error message ? Look in `storage/logs/flarum.log`, your webserver logs or enable debug mode and click the more details button.

The second "issue" is actually a feature. It was made so you can't forget to save the the answer list/order (because it's unclear whether add would save the entry or not)... It has the side effect of triggering the creation immediately when creating a new field. Tracking this in #27

**Comment by clarkwinkelmann** [comment] 2019-07-02 09:45
As we've heard no new feedback since last year and the extension was heavily rewritten for beta 8, the issue is probably no longer relevant, so I'm closing it.

If you still experience it, let us know and we'll re-open.

**Closed by clarkwinkelmann** 2019-07-02 09:45 UTC
Labels: bug
